import { Language, Translations, Gender, Preset, QuickTag } from './types';

export const TRANSLATIONS: Translations = {
  [Language.EN]: {
    title: "Makeupify",
    subtitle: "AI Powered Makeup Artist",
    uploadStep: "Upload Your Photo",
    uploadDesc: "Choose a clear portrait photo for best results.",
    genderStep: "Select Gender",
    male: "Male",
    female: "Female",
    methodStep: "Choose Makeup Method",
    methodPreset: "Style Presets",
    methodText: "Describe Look",
    methodTransfer: "Style Transfer",
    methodTransferDesc: "Upload a photo with the makeup look you want to copy.",
    generate: "Apply Makeup",
    generating: "Applying Makeup...",
    error: "Something went wrong. Please try again.",
    retry: "Retry",
    download: "Download Result",
    back: "Back",
    startOver: "Start New",
    textPlaceholder: "E.g., Red lipstick, smoky eyes, and contoured cheeks...",
    transferPlaceholder: "Upload Reference Image",
    recommendationTitle: "AI Recommendations",
    recommendationBody: "Based on your face shape, we recommend highlighting your cheekbones and using a warm tone for your lips to enhance your natural glow.",
    adModalTitle: "Watch Ad to Continue?",
    adModalBody: "Please watch a short ad to support our free tool.",
    yes: "Yes",
    no: "No",
    adWatching: "Watching Ad...",
    quickTagsLabel: "Quick Add:",
    presets: {
      natural: "Natural Glow",
      glam: "Hollywood Glam",
      gothic: "Dark Gothic",
      bridal: "Soft Bridal",
      editorial: "High Fashion",
      grooming: "Clean Grooming",
      kpop: "K-Pop Idol",
      punk: "Punk Rock",
      acne: "Remove Acne",
      wrinkle: "Remove Wrinkles",
      smooth: "Skin Smoothing"
    },
    tags: {
      redLipstick: "Red Lipstick",
      pinkBlush: "Pink Blush",
      catEye: "Cat Eye Liner",
      contour: "Contour",
      foundation: "Matte Foundation",
      smokeyEye: "Smokey Eyes",
      highlighter: "Highlighter"
    }
  },
  [Language.TR]: {
    title: "Makeupify",
    subtitle: "Yapay Zeka Destekli Makyaj Editörü",
    uploadStep: "Fotoğrafını Yükle",
    uploadDesc: "En iyi sonuç için net bir portre fotoğrafı seçin.",
    genderStep: "Cinsiyet Seçimi",
    male: "Erkek",
    female: "Kadın",
    methodStep: "Makyaj Yöntemi",
    methodPreset: "Hazır Stiller",
    methodText: "Tarif Et",
    methodTransfer: "Stil Transferi",
    methodTransferDesc: "Kopyalamak istediğiniz makyaj stilini içeren bir fotoğraf yükleyin.",
    generate: "Makyajı Uygula",
    generating: "Makyaj Uygulanıyor...",
    error: "Bir hata oluştu. Lütfen tekrar deneyin.",
    retry: "Tekrar Dene",
    download: "Sonucu İndir",
    back: "Geri",
    startOver: "Baştan Başla",
    textPlaceholder: "Örn: Kırmızı ruj, dumanlı gözler ve kontür...",
    transferPlaceholder: "Referans Görsel Yükle",
    recommendationTitle: "Yapay Zeka Tavsiyesi",
    recommendationBody: "Yüz hatlarınıza göre, elmacık kemiklerinizi belirginleştirmenizi ve doğal ışıltınızı artırmak için dudaklarınızda sıcak bir ton kullanmanızı öneririz.",
    adModalTitle: "Devam Etmek İçin Reklam İzle",
    adModalBody: "Ücretsiz aracımızı desteklemek için lütfen kısa bir reklam izleyiniz.",
    yes: "Evet",
    no: "Hayır",
    adWatching: "Reklam İzleniyor...",
    quickTagsLabel: "Hızlı Ekle:",
    presets: {
      natural: "Doğal Işıltı",
      glam: "Hollywood Işıltısı",
      gothic: "Gotik",
      bridal: "Gelin Makyajı",
      editorial: "Moda Çekimi",
      grooming: "Temiz Bakım",
      kpop: "K-Pop İdolü",
      punk: "Punk Rock",
      acne: "Sivilce Silme",
      wrinkle: "Kırışıklık Giderme",
      smooth: "Cilt Pürüzsüzleştirme"
    },
    tags: {
      redLipstick: "Kırmızı Ruj",
      pinkBlush: "Pembe Allık",
      catEye: "Kedi Gözü Eyeliner",
      contour: "Kontür",
      foundation: "Mat Fondöten",
      smokeyEye: "Dumanlı Gözler",
      highlighter: "Aydınlatıcı"
    }
  },
  [Language.ES]: {
    title: "Makeupify",
    subtitle: "Artista de Maquillaje IA",
    uploadStep: "Sube tu Foto",
    uploadDesc: "Elige una foto de retrato clara para mejores resultados.",
    genderStep: "Seleccionar Género",
    male: "Hombre",
    female: "Mujer",
    methodStep: "Método de Maquillaje",
    methodPreset: "Estilos Predefinidos",
    methodText: "Describir",
    methodTransfer: "Transferencia de Estilo",
    methodTransferDesc: "Sube una foto con el maquillaje que deseas copiar.",
    generate: "Aplicar Maquillaje",
    generating: "Aplicando Maquillaje...",
    error: "Algo salió mal. Por favor inténtalo de nuevo.",
    retry: "Reintentar",
    download: "Descargar Resultado",
    back: "Atrás",
    startOver: "Empezar de Nuevo",
    textPlaceholder: "Ej: Labios rojos, ojos ahumados...",
    transferPlaceholder: "Subir Imagen de Referencia",
    recommendationTitle: "Recomendaciones de IA",
    recommendationBody: "Según la forma de tu rostro, recomendamos resaltar tus pómulos y usar un tono cálido.",
    adModalTitle: "¿Ver anuncio para continuar?",
    adModalBody: "Por favor mira un anuncio corto para apoyar nuestra herramienta gratuita.",
    yes: "Sí",
    no: "No",
    adWatching: "Viendo Anuncio...",
    quickTagsLabel: "Añadir rápido:",
    presets: {
      natural: "Brillo Natural",
      glam: "Glamour Hollywood",
      gothic: "Gótico Oscuro",
      bridal: "Novia Suave",
      editorial: "Alta Moda",
      grooming: "Aseo Limpio",
      kpop: "Ídolo K-Pop",
      punk: "Punk Rock",
      acne: "Eliminar Acné",
      wrinkle: "Eliminar Arrugas",
      smooth: "Suavizar Piel"
    },
    tags: {
      redLipstick: "Labios Rojos",
      pinkBlush: "Rubor Rosa",
      catEye: "Delineado Gato",
      contour: "Contorno",
      foundation: "Base Mate",
      smokeyEye: "Ojos Ahumados",
      highlighter: "Iluminador"
    }
  },
  [Language.PT]: {
    title: "Makeupify",
    subtitle: "Artista de Maquiagem IA",
    uploadStep: "Envie sua Foto",
    uploadDesc: "Escolha uma foto de retrato clara.",
    genderStep: "Selecione o Gênero",
    male: "Masculino",
    female: "Feminino",
    methodStep: "Método de Maquiagem",
    methodPreset: "Estilos Predefinidos",
    methodText: "Descrever",
    methodTransfer: "Transferência de Estilo",
    methodTransferDesc: "Envie uma foto com a maquiagem que deseja copiar.",
    generate: "Aplicar Maquiagem",
    generating: "Aplicando Maquiagem...",
    error: "Algo deu errado. Tente novamente.",
    retry: "Tentar Novamente",
    download: "Baixar Resultado",
    back: "Voltar",
    startOver: "Recomeçar",
    textPlaceholder: "Ex: Batom vermelho, olhos esfumados...",
    transferPlaceholder: "Carregar Imagem de Referência",
    recommendationTitle: "Recomendações de IA",
    recommendationBody: "Com base no seu rosto, recomendamos realçar as maçãs do rosto e usar tons quentes.",
    adModalTitle: "Assistir anúncio?",
    adModalBody: "Por favor, assista a um anúncio curto para continuar.",
    yes: "Sim",
    no: "Não",
    adWatching: "Assistindo Anúncio...",
    quickTagsLabel: "Adicionar rápido:",
    presets: {
      natural: "Brilho Natural",
      glam: "Glamour Hollywood",
      gothic: "Gótico",
      bridal: "Noiva Suave",
      editorial: "Editorial",
      grooming: "Visual Limpo",
      kpop: "Ídolo K-Pop",
      punk: "Punk Rock",
      acne: "Remover Acne",
      wrinkle: "Remover Rugas",
      smooth: "Suavizar Pele"
    },
    tags: {
      redLipstick: "Batom Vermelho",
      pinkBlush: "Blush Rosa",
      catEye: "Delineado Gatinho",
      contour: "Contorno",
      foundation: "Base Matte",
      smokeyEye: "Olhos Esfumados",
      highlighter: "Iluminador"
    }
  },
  [Language.DE]: {
    title: "Makeupify",
    subtitle: "KI Makeup Artist",
    uploadStep: "Foto hochladen",
    uploadDesc: "Wählen Sie ein klares Porträtfoto.",
    genderStep: "Geschlecht wählen",
    male: "Männlich",
    female: "Weiblich",
    methodStep: "Make-up Methode",
    methodPreset: "Stil-Voreinstellungen",
    methodText: "Beschreiben",
    methodTransfer: "Stil-Transfer",
    methodTransferDesc: "Laden Sie ein Foto mit dem gewünschten Make-up hoch.",
    generate: "Make-up anwenden",
    generating: "Make-up wird angewendet...",
    error: "Etwas ist schief gelaufen. Bitte versuchen Sie es erneut.",
    retry: "Erneut versuchen",
    download: "Ergebnis herunterladen",
    back: "Zurück",
    startOver: "Neu starten",
    textPlaceholder: "Z.B. Roter Lippenstift, Smoky Eyes...",
    transferPlaceholder: "Referenzbild hochladen",
    recommendationTitle: "KI-Empfehlungen",
    recommendationBody: "Basierend auf Ihrer Gesichtsform empfehlen wir, Ihre Wangenknochen zu betonen.",
    adModalTitle: "Werbung ansehen?",
    adModalBody: "Bitte sehen Sie sich eine kurze Werbung an, um fortzufahren.",
    yes: "Ja",
    no: "Nein",
    adWatching: "Werbung läuft...",
    quickTagsLabel: "Schnell hinzufügen:",
    presets: {
      natural: "Natürlicher Glanz",
      glam: "Hollywood Glamour",
      gothic: "Dunkel Goth",
      bridal: "Braut Make-up",
      editorial: "High Fashion",
      grooming: "Gepflegt",
      kpop: "K-Pop Idol",
      punk: "Punk Rock",
      acne: "Akne entfernen",
      wrinkle: "Falten entfernen",
      smooth: "Hautglättung"
    },
    tags: {
      redLipstick: "Roter Lippenstift",
      pinkBlush: "Rosa Rouge",
      catEye: "Cat Eye",
      contour: "Konturierung",
      foundation: "Matt-Foundation",
      smokeyEye: "Smokey Eyes",
      highlighter: "Highlighter"
    }
  },
  [Language.FR]: {
    title: "Makeupify",
    subtitle: "Artiste Maquilleur IA",
    uploadStep: "Téléchargez votre photo",
    uploadDesc: "Choisissez un portrait clair.",
    genderStep: "Sélectionner le genre",
    male: "Homme",
    female: "Femme",
    methodStep: "Méthode de maquillage",
    methodPreset: "Styles prédéfinis",
    methodText: "Décrire",
    methodTransfer: "Transfert de style",
    methodTransferDesc: "Téléchargez une photo avec le maquillage souhaité.",
    generate: "Appliquer le maquillage",
    generating: "Application en cours...",
    error: "Une erreur est survenue. Veuillez réessayer.",
    retry: "Réessayer",
    download: "Télécharger",
    back: "Retour",
    startOver: "Recommencer",
    textPlaceholder: "Ex: Rouge à lèvres rouge, yeux fumés...",
    transferPlaceholder: "Image de référence",
    recommendationTitle: "Recommandations IA",
    recommendationBody: "Selon la forme de votre visage, nous recommandons de souligner vos pommettes.",
    adModalTitle: "Regarder une publicité ?",
    adModalBody: "Veuillez regarder une courte publicité pour continuer.",
    yes: "Oui",
    no: "Non",
    adWatching: "Publicité en cours...",
    quickTagsLabel: "Ajout rapide :",
    presets: {
      natural: "Éclat Naturel",
      glam: "Glamour Hollywood",
      gothic: "Gothique",
      bridal: "Mariée Douce",
      editorial: "Haute Couture",
      grooming: "Soigné",
      kpop: "Idole K-Pop",
      punk: "Punk Rock",
      acne: "Enlever l'acné",
      wrinkle: "Enlever les rides",
      smooth: "Lissage peau"
    },
    tags: {
      redLipstick: "Rouge à lèvres",
      pinkBlush: "Fard rose",
      catEye: "Yeux de chat",
      contour: "Contouring",
      foundation: "Fond de teint mat",
      smokeyEye: "Yeux fumés",
      highlighter: "Enlumineur"
    }
  },
  [Language.JP]: {
    title: "Makeupify",
    subtitle: "AIメイクアップアーティスト",
    uploadStep: "写真をアップロード",
    uploadDesc: "鮮明なポートレート写真を選んでください。",
    genderStep: "性別を選択",
    male: "男性",
    female: "女性",
    methodStep: "メイク方法",
    methodPreset: "スタイルプリセット",
    methodText: "説明する",
    methodTransfer: "スタイル転写",
    methodTransferDesc: "真似したいメイクの写真をアップロードしてください。",
    generate: "メイクを適用",
    generating: "メイク適用中...",
    error: "エラーが発生しました。もう一度お試しください。",
    retry: "再試行",
    download: "結果をダウンロード",
    back: "戻る",
    startOver: "最初から",
    textPlaceholder: "例：赤い口紅、スモーキーアイ...",
    transferPlaceholder: "参考画像をアップロード",
    recommendationTitle: "AIのおすすめ",
    recommendationBody: "あなたの顔の形に基づいて、頬骨を強調し、温かみのあるトーンを使用することをお勧めします。",
    adModalTitle: "広告を見て続けますか？",
    adModalBody: "無料ツールをサポートするために短い広告をご覧ください。",
    yes: "はい",
    no: "いいえ",
    adWatching: "広告を再生中...",
    quickTagsLabel: "クイック追加:",
    presets: {
      natural: "ナチュラルグロウ",
      glam: "ハリウッドグラム",
      gothic: "ゴシック",
      bridal: "ブライダル",
      editorial: "ハイファッション",
      grooming: "グルーミング",
      kpop: "K-POPアイドル",
      punk: "パンクロック",
      acne: "ニキビ消し",
      wrinkle: "シワ消し",
      smooth: "美肌補正"
    },
    tags: {
      redLipstick: "赤い口紅",
      pinkBlush: "ピンクチーク",
      catEye: "キャットアイ",
      contour: "コントゥアリング",
      foundation: "マットファンデ",
      smokeyEye: "スモーキーアイ",
      highlighter: "ハイライト"
    }
  },
  [Language.KO]: {
    title: "Makeupify",
    subtitle: "AI 메이크업 아티스트",
    uploadStep: "사진 업로드",
    uploadDesc: "선명한 인물 사진을 선택하세요.",
    genderStep: "성별 선택",
    male: "남성",
    female: "여성",
    methodStep: "메이크업 방법",
    methodPreset: "스타일 프리셋",
    methodText: "설명하기",
    methodTransfer: "스타일 전송",
    methodTransferDesc: "따라하고 싶은 메이크업 사진을 업로드하세요.",
    generate: "메이크업 적용",
    generating: "메이크업 적용 중...",
    error: "오류가 발생했습니다. 다시 시도해 주세요.",
    retry: "재시도",
    download: "결과 다운로드",
    back: "뒤로",
    startOver: "처음부터",
    textPlaceholder: "예: 빨간 립스틱, 스모키 눈화장...",
    transferPlaceholder: "참조 이미지 업로드",
    recommendationTitle: "AI 추천",
    recommendationBody: "얼굴형에 따라 광대뼈를 강조하고 따뜻한 톤을 사용하는 것을 추천합니다.",
    adModalTitle: "광고를 보고 계속하시겠습니까?",
    adModalBody: "무료 도구를 지원하기 위해 짧은 광고를 시청해 주세요.",
    yes: "예",
    no: "아니요",
    adWatching: "광고 시청 중...",
    quickTagsLabel: "빠른 추가:",
    presets: {
      natural: "내추럴 글로우",
      glam: "할리우드 글램",
      gothic: "고딕",
      bridal: "브라이덜",
      editorial: "하이 패션",
      grooming: "깔끔한 그루밍",
      kpop: "K-POP 아이돌",
      punk: "펑크 록",
      acne: "여드름 제거",
      wrinkle: "주름 제거",
      smooth: "피부 보정"
    },
    tags: {
      redLipstick: "빨간 립스틱",
      pinkBlush: "핑크 블러셔",
      catEye: "캣아이",
      contour: "윤곽 메이크업",
      foundation: "매트 파운데이션",
      smokeyEye: "스모키 아이",
      highlighter: "하이라이터"
    }
  },
  [Language.AR]: {
    title: "Makeupify",
    subtitle: "فنان مكياج بالذكاء الاصطناعي",
    uploadStep: "حمل صورتك",
    uploadDesc: "اختر صورة شخصية واضحة للحصول على أفضل النتائج.",
    genderStep: "اختر الجنس",
    male: "ذكر",
    female: "أنثى",
    methodStep: "طريقة المكياج",
    methodPreset: "أنماط جاهزة",
    methodText: "وصف",
    methodTransfer: "نقل النمط",
    methodTransferDesc: "قم بتحميل صورة تحتوي على مظهر المكياج الذي تريد نسخه.",
    generate: "تطبيق المكياج",
    generating: "جاري تطبيق المكياج...",
    error: "حدث خطأ ما. يرجى المحاولة مرة أخرى.",
    retry: "إعادة المحاولة",
    download: "تنزيل النتيجة",
    back: "رجوع",
    startOver: "البدء من جديد",
    textPlaceholder: "مثال: أحمر شفاه أحمر، عيون دخانية...",
    transferPlaceholder: "تحميل الصورة المرجعية",
    recommendationTitle: "توصيات الذكاء الاصطناعي",
    recommendationBody: "بناءً على شكل وجهك، نوصي بإبراز عظام الخد واستخدام نغمة دافئة.",
    adModalTitle: "مشاهدة إعلان للمتابعة؟",
    adModalBody: "يرجى مشاهدة إعلان قصير لدعم أداتنا المجانية.",
    yes: "نعم",
    no: "لا",
    adWatching: "مشاهدة الإعلان...",
    quickTagsLabel: "إضافة سريعة:",
    presets: {
      natural: "توهج طبيعي",
      glam: "بريق هوليوود",
      gothic: "قوطي داكن",
      bridal: "زفاف ناعم",
      editorial: "موضة راقية",
      grooming: "عناية نظيفة",
      kpop: "نجم كيبوب",
      punk: "بانك روك",
      acne: "إزالة حب الشباب",
      wrinkle: "إزالة التجاعيد",
      smooth: "تنعيم البشرة"
    },
    tags: {
      redLipstick: "أحمر شفاه أحمر",
      pinkBlush: "أحمر خدود وردي",
      catEye: "كحل عين القطة",
      contour: "كونتور",
      foundation: "كريم أساس",
      smokeyEye: "عيون دخانية",
      highlighter: "هايلاتير"
    }
  }
};

export const MAKEUP_PRESETS: Preset[] = [
  // Styles
  { id: 'natural', labelKey: 'natural', prompt: "Apply a very subtle, natural makeup look. Dewy skin, light mascara, tinted lip balm, soft blush.", gender: [Gender.FEMALE, Gender.MALE], category: 'style' },
  { id: 'glam', labelKey: 'glam', prompt: "Apply a full Hollywood glam makeup look. Bold red lipstick, winged eyeliner, contouring, highlighter, false lashes.", gender: [Gender.FEMALE], category: 'style' },
  { id: 'gothic', labelKey: 'gothic', prompt: "Apply a gothic makeup look. Dark eyeshadow, black lipstick, pale skin foundation, sharp contour.", gender: [Gender.FEMALE, Gender.MALE], category: 'style' },
  { id: 'bridal', labelKey: 'bridal', prompt: "Apply a soft bridal makeup look. Rose gold eyeshadow, pink blush, satin finish lips, glowing skin.", gender: [Gender.FEMALE], category: 'style' },
  { id: 'editorial', labelKey: 'editorial', prompt: "Apply an avant-garde high fashion editorial makeup look. Graphic liner, bold colors, artistic shapes on face.", gender: [Gender.FEMALE, Gender.MALE], category: 'style' },
  { id: 'grooming', labelKey: 'grooming', prompt: "Apply male grooming makeup. Concealer for blemishes, subtle bronzer, groomed eyebrows, matte lip balm.", gender: [Gender.MALE], category: 'style' },
  { id: 'kpop', labelKey: 'kpop', prompt: "Apply K-Pop idol style makeup. Glass skin, coral eyeshadow, straight brows, gradient lips (if female) or subtle tint (if male).", gender: [Gender.FEMALE, Gender.MALE], category: 'style' },
  { id: 'punk', labelKey: 'punk', prompt: "Apply punk rock makeup. Smudged heavy eyeliner, dark colors, rebellious aesthetic.", gender: [Gender.FEMALE, Gender.MALE], category: 'style' },
  // Retouch
  { id: 'acne', labelKey: 'acne', prompt: "Remove all acne, blemishes, and redness from the face. Keep the skin texture natural but clear. Do not apply other makeup.", gender: [Gender.FEMALE, Gender.MALE], category: 'retouch' },
  { id: 'wrinkle', labelKey: 'wrinkle', prompt: "Soften and remove deep wrinkles and fine lines. Rejuvenate the skin appearance while keeping it realistic.", gender: [Gender.FEMALE, Gender.MALE], category: 'retouch' },
  { id: 'smooth', labelKey: 'smooth', prompt: "Apply skin smoothing and pore reduction. Create a flawless complexion. Retain facial features perfectly.", gender: [Gender.FEMALE, Gender.MALE], category: 'retouch' },
];

export const QUICK_TAGS: QuickTag[] = [
  { id: 'redLipstick', labelKey: 'redLipstick', value: "Red Lipstick" },
  { id: 'pinkBlush', labelKey: 'pinkBlush', value: "Pink Blush" },
  { id: 'catEye', labelKey: 'catEye', value: "Cat Eye Eyeliner" },
  { id: 'contour', labelKey: 'contour', value: "Sharp Contour" },
  { id: 'foundation', labelKey: 'foundation', value: "Matte Foundation" },
  { id: 'smokeyEye', labelKey: 'smokeyEye', value: "Smokey Eyes" },
  { id: 'highlighter', labelKey: 'highlighter', value: "Highlighter on cheekbones" },
];